// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsgEXu3xxIMTsKOXrO_FKbeN1gJE8mPIU',
    appId: '1:163662132478:web:836844fe91d4680b5de1af',
    messagingSenderId: '163662132478',
    projectId: 'market-rental-application',
    authDomain: 'market-rental-application.firebaseapp.com',
    databaseURL: 'https://market-rental-application-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'market-rental-application.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGmf-HaqDbWfnOh8o26z2Y4XlLw0sgEXk',
    appId: '1:163662132478:android:172075157afb193a5de1af',
    messagingSenderId: '163662132478',
    projectId: 'market-rental-application',
    databaseURL: 'https://market-rental-application-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'market-rental-application.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrEsxdE53AAiOa0Nki7hLgCqwe8p09qhA',
    appId: '1:163662132478:ios:756647dfcfde05175de1af',
    messagingSenderId: '163662132478',
    projectId: 'market-rental-application',
    databaseURL: 'https://market-rental-application-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'market-rental-application.firebasestorage.app',
    iosBundleId: 'com.example.marketSlotRental',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrEsxdE53AAiOa0Nki7hLgCqwe8p09qhA',
    appId: '1:163662132478:ios:756647dfcfde05175de1af',
    messagingSenderId: '163662132478',
    projectId: 'market-rental-application',
    databaseURL: 'https://market-rental-application-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'market-rental-application.firebasestorage.app',
    iosBundleId: 'com.example.marketSlotRental',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsgEXu3xxIMTsKOXrO_FKbeN1gJE8mPIU',
    appId: '1:163662132478:web:2400910f677dafc95de1af',
    messagingSenderId: '163662132478',
    projectId: 'market-rental-application',
    authDomain: 'market-rental-application.firebaseapp.com',
    databaseURL: 'https://market-rental-application-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'market-rental-application.firebasestorage.app',
  );
}
